data:extend({
  {
    type = "string-setting",
    name = "primary-mode",
    setting_type = "runtime-per-user",
    default_value = "overwrite",
    allowed_values = { "overwrite", "additive" },
    order = '2a',
  },
  {
    type = "string-setting",
    name = "alternate-mode",
    setting_type = "runtime-per-user",
    default_value = "additive",
    allowed_values = { "disabled", "overwrite", "additive" },
    order = '2b',
  },
  {
    type = "string-setting",
    name = "multiplier-mode",
    setting_type = "runtime-per-user",
    default_value = "duration-speed",
    allowed_values = { "constant-recipes", "constant-items", "constant-stacks", "duration-base", "duration-speed" },
    order = '4a',
  },
  {
    type = "int-setting",
    name = "multiplier-duration",
    setting_type = "runtime-per-user",
    default_value = 30,
    minimum_value = 1,
    maximum_value = 600,
    order = '4b',
  },
  {
    type = "int-setting",
    name = "multiplier-constant",
    setting_type = "runtime-per-user",
    default_value = 1,
    minimum_value = 1,
    maximum_value = 1000,
    order = '4c',
  },
})
